baseURL = "https://rfiilho.netlify.app/"
languageCode = "pt-br"
title = "Renato Filho"
theme = "anatole"

name = "Anatole"
license = "MIT"
licenselink = "https://github.com/lxndrblz/anatole/blob/master/LICENSE"
description = "Anatole is a beautiful minimalist two-column hugo theme based on farbox-theme-Anatole."
homepage = "https://github.com/lxndrblz/anatole/"
tags = ["blog", "responsive", "clean", "minimalist", "minimal", "personal", "dark"]
features = ["blog", "seo", "responsive", "mobile", "disqus", "fontawesome", "analytics", "math"]
min_version = "0.53.0"

[author]
  name = "Renato Filho"
  homepage = "https://alexbilz.com"
